#!/bin/sh

FILE=/tmp/dictionary-$$

#read EXPR
#echo $EXPR | sed 's/\([^0-9]\)\([^0-9]\)/\1 \2/g; s/\([0-9]\+\)\([^0-9]\)/\1 \2/g; s/\([^0-9]\)\([0-9]\+\)/\1 \2/g; s/\([*()]\)/\\\1/g; s/^/expr /' > $FILE
read INPUT

curl -s "http://semes-olla.rhcloud.com/word?$INPUT&Swadesh/Turkic/Kazakh.py"
EXIT_STATUS=$?
rm -f $FILE
exit $EXIT_STATUS
